### ISSUE TITLE
AUTO FOLLOWS GITHUB REPOS

### ISSUE THREAD

**Issue by philipheinser** [gitscout/gitscout-feedback#65] opened 2016-12-09 04:04 UTC
I just downloaded the mac app and logged in. It used my github credentials to watch github repos that i before login in didnt watched. This is not okay!

**Comment by jeremybenaim** [comment] 2016-12-09 05:57
@philipheinser closing this one as its a duplicate of #62 (but feel free to join the conversation there)

**Closed by jeremybenaim** 2016-12-09 05:57 UTC
