### ISSUE TITLE
Github projects support

### ISSUE THREAD

**Issue by shinzui** [gitscout/gitscout-feedback#152] opened 2017-02-04 15:30 UTC
It would be amazing if gitscout supported github projects. We heavily use projects to organize issues inside a repo, and across repos (on the organization level). I have to still go to github to place the issue in the correct column in a project, so it's easier to create issues from github. I would love to only use gitscout.

**Comment by onbjerg** [comment] 2017-08-29 15:40
Duplicate of #61? 😊

**Comment by jeremybenaim** [comment] 2018-03-02 12:00
Closing because of duplicate, yes ☺️

**Closed by jeremybenaim** 2018-03-02 12:00 UTC
Labels: feature request
