### ISSUE TITLE
[Feature request] Support for zenhub

### ISSUE THREAD

**Issue by toblan** [gitscout/gitscout-feedback#107] opened 2017-01-03 07:32 UTC
As working with epics and having boards from zenhub eases the workflow of handling issues, it woud be great to integrate that into git scout.

**Comment by roberteles** [comment] 2017-01-03 10:11
This is a duplicate of #84.

**Comment by jeremybenaim** [comment] 2017-01-04 09:10
@toblan yep, @roberteles is right. Closing this one, but thanks for letting us know your feedback 😊

**Closed by jeremybenaim** 2017-01-04 09:10 UTC
Labels: duplicate
